### ISSUE TITLE
Incorrect pronouns in conversation with Meghyn and Nat

### ISSUE THREAD

**Issue by VoilaTada** [mastermind107/TOTK-Rinkuru-Dialogue-Mod#1]
The two traveling girls that wanted brightcaps have unchanged dialogue. There's a few lines where he/him pronouns are used, but I only managed to snag a screenshot of one line. Hopefullly the other lines will be easy to find with this. Sorry for any inconvenience, and thank you for the mod!
Screenshot of one line [here](https://i.imgur.com/KlUVRHu.jpeg).

**Comment by mastermind107** [comment]
Thanks for reporting this issue. I think I got all of the errors, but I will probably need to double check it later in game. It is usually easy to find any other issues as long as I have part of the conversation so I can find what file the dialogue is found in.
